export default [
  {
    id: 1,
    Question: "Question number one",
    Answer1: "Answer 1",
    Answer2: "Answer 2",
    Answer3: "Answer 3",
    Answer4: "Answer 4",
  },
  {
    id: 2,
    Question: "Question number two",
    Answer1: "Answer 1",
    Answer2: "Answer 2",
    Answer3: "Answer 3",
    Answer4: "Answer 4",
  },
  {
    id: 3,
    Question: "Question number three",
    Answer1: "Answer 1",
    Answer2: "Answer 2",
    Answer3: "Answer 3",
    Answer4: "Answer 4",
  },
  {
    id: 4,
    Question: "Question number four",
    Answer1: "Answer 1",
    Answer2: "Answer 2",
    Answer3: "Answer 3",
    Answer4: "Answer 4",
  },
  {
    id: 5,
    Question: "Question number five",
    Answer1: "Answer 1",
    Answer2: "Answer 2",
    Answer3: "Answer 3",
    Answer4: "Answer 4",
  },
  {
    id: 6,
    Question: "Question number six",
    Answer1: "Answer 1",
    Answer2: "Answer 2",
    Answer3: "Answer 3",
    Answer4: "Answer 4",
  },
];
