export default [
  {
    id: 1,
    question: "How many people live in berlin",
    answer1: "10",
    answer2: "3.000000",
    answer3: "800000",
    answer4: "350000",
  },
  {
    id: 2,
    question: "Question number two",
    answer1: "Answer 1",
    answer2: "Answer 2",
    answer3: "Answer 3",
    answer4: "Answer 4",
  },
  {
    id: 3,
    question: "Question number three",
    answer1: "Answer 1",
    answer2: "Answer 2",
    answer3: "Answer 3",
    answer4: "Answer 4",
  },
  {
    id: 4,
    question: "Question number four",
    answer1: "Answer 1",
    answer2: "Answer 2",
    answer3: "Answer 3",
    answer4: "Answer 4",
  },
  {
    id: 5,
    question: "Question number five",
    answer1: "Answer 1",
    answer2: "Answer 2",
    answer3: "Answer 3",
    answer4: "Answer 4",
  },
  {
    id: 6,
    question: "Question number six",
    answer1: "Answer 1",
    answer2: "Answer 2",
    answer3: "Answer 3",
    answer4: "Answer 4",
  },
];
